name: Exemplo de Fluxo de Trabalho

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Configurar Ambiente
      run: |
        echo "Iniciando o comando PowerShell..."
        
        # Execute o comando Get-LocalUser e capture a saída
        $localUsers = Get-LocalUser

        # Exiba a saída para depuração
        echo "Saída do comando Get-LocalUser:"
        echo "$localUsers"
      shell: pwsh

    - name: Outro Passo
      run: |
        # Outro comando ou etapa
      shell: pwsh
