name: FREE VPS - By Humberto

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Fazendo as configurações básicas...
        run: |
          Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-RemoteDesktopServices-Server-Feature
          Start-Service TermService
          Set-Service -Name TermService -StartupType 'Automatic'
          New-LocalUser -Name Humberto -Description "Usuário do Humberto's VPS"
          Set-LocalUser -Name Humberto -Password (ConvertTo-SecureString -AsPlainText "Humberto@#123" -Force)
          Add-LocalGroupMember -Group "Administradores" -Member Humberto
          Get-LocalUser
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-386.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath "ngrok"
          Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "Humberto@#123" -Force)
          cd ngrok
          ngrok config add-authtoken 26l2eR5cm1MuLRoKVXkVn3UQzHk_6WzTXhwxmHegKUvQsxwVu
          ngrok tcp 3389 --region sa &
