name: FREE VPS - By Humberto

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fazendo as configurações básicas...
        run: |
           sudo apt update
           sudo apt update
           sudo apt install qemu-kvm qemu-utils
           sudo apt install tigervnc-scraping-server
           qemu-img create -f qcow2 disk.qcow2 20G
           wget https://archive.org/download/windows-10-20-h-2_202203/Windows%2010%2021H2.iso
           mv Windows%2010%2021H2.iso windows.iso
           nohup qemu-system-x86_64 -cdrom windows.iso -hda disk.qcow2 -m 7024 -vnc :1 -k en-us &
           curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
           ngrok config add-authtoken 26l2eR5cm1MuLRoKVXkVn3UQzHk_6WzTXhwxmHegKUvQsxwVu
           nohup ngrok tcp --region sa 5901 &
           


