# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Fazendo as configurações basicas...
        run: |
          New-LocalUser -Name Humberto -Description "Usuário do Humberto's VPS"
          Set-LocalUser -Name Humberto -Password (ConvertTo-SecureString -AsPlainText "Humberto@#123" -Force)
          Add-LocalGroupMember -Group "Administradores" -Member Humberto
          Get-LocalUser
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-386.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath "ngrok"
          Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "Humberto@#123" -Force)
          cd ngrok
          ngrok config add-authtoken 26l2eR5cm1MuLRoKVXkVn3UQzHk_6WzTXhwxmHegKUvQsxwVu
          ngrok tcp 3389 --region sa &

      # Runs a set of commands using the runners shell
      - name: Conclusão
        run: |
          echo Deploy feito com sucesso!
          echo Feito por Humberto
